# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Iuliia Lisitcyna
title: Junior iOS Developer
email: julia.Lisicina92@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
github_username:  Jf0x
# dribbble_username: jekyll
facebook_username: Jullisss
# flickr_username: jekyll
instagram_username: julia_lisicina
linkedin_username: https://www.linkedin.com/in/julia-lisitcyna-225488195/
# pinterest_username: 
# youtube_username: 
# googleplus_username: 

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Iuliia and I'm a iOS Developer. 

  I’m passionate and hardworking, and eager to solve each problem that comes my way. I learn quickly and have a productive attitude.

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and mobil application engineering some of my other interests and hobbies are:
   - surfing
   - rolling
   - hiking
   
## Projects Section
## projects_title: Projects

# Experience Section
# experience_title: Experience

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
